octane-eclipse-plugin/src/com/hpe/octane/ideplugins/eclipse/ui/comment/EntityCommentComposite.java
=> Defect #589045: Fixed bug where you can't open a linked entity from

octane-eclipse-plugin/src/com/hpe/octane/ideplugins/eclipse/ui/comment/EntityCommentComposite.java
I don't like this solution because it takes way too specific texts and seems kind of random/hard coded, but it works (both on macOS and windows) . I will try to search for something else.
=> Defect comments (Defect #589045)

octane-eclipse-plugin/src/com/hpe/octane/ideplugins/eclipse/ui/entitydetail/EntityHeaderComposite.java, octane-eclipse-plugin/src/com/hpe/octane/ideplugins/eclipse/ui/entitydetail/EntityModelEditor.java, octane-eclipse-plugin/src/com/hpe/octane/ideplugins/eclipse/ui/entitylist/EntityTypeSelectorComposite.java, octane-eclipse-plugin/src/com/hpe/octane/ideplugins/eclipse/util/PredefinedEntityComparator.java
Field dropdown content sorted alphabetically
Field filter sorted with hardcoded entity type comparator, same that's used to sort the entities in the list by type
=> Fields dropdown sorting

octane-eclipse-plugin/src/com/hpe/octane/ideplugins/eclipse/ui/comment/EntityCommentComposite.java, octane-eclipse-plugin/src/com/hpe/octane/ideplugins/eclipse/ui/entitydetail/field/DescriptionComposite.java
[https://github.com/MicroFocus/octane-eclipse-plugin/pull/46/files?w=1](https://github.com/MicroFocus/octane-eclipse-plugin/pull/46/files?w=1)
=> Defect #610066: Fixed bug where ubuntu is green in SWT.Browser

octane-eclipse-plugin/src/com/hpe/octane/ideplugins/eclipse/ui/comment/EntityCommentComposite.java, octane-eclipse-plugin/src/com/hpe/octane/ideplugins/eclipse/ui/entitydetail/field/DescriptionComposite.java
Didn't think it affected also the font. same fix
=> Font color

octane-eclipse-plugin/src/com/hpe/octane/ideplugins/eclipse/ui/comment/EntityCommentComposite.java, octane-eclipse-plugin/src/com/hpe/octane/ideplugins/eclipse/ui/entitydetail/field/DescriptionComposite.java, octane-eclipse-plugin/src/com/hpe/octane/ideplugins/eclipse/ui/util/LinkInterceptListener.java
Fixed bug for Ubuntu where when you try to open a link to another entity from description, it would crash
=> Defect #622076: Fixed bug where it wouldn't open a link in another

octane-eclipse-plugin/src/com/hpe/octane/ideplugins/eclipse/ui/comment/EntityCommentComposite.java, octane-eclipse-plugin/src/com/hpe/octane/ideplugins/eclipse/ui/comment/job/GetCommentsJob.java, octane-eclipse-plugin/src/com/hpe/octane/ideplugins/eclipse/ui/comment/job/PostCommentJob.java, octane-eclipse-plugin/src/com/hpe/octane/ideplugins/eclipse/ui/entitydetail/field/EntityPhaseComposite.java, octane-eclipse-plugin/src/com/hpe/octane/ideplugins/eclipse/ui/entitydetail/job/GetPossiblePhasesJob.java, octane-eclipse-plugin/src/com/hpe/octane/ideplugins/eclipse/ui/mywork/MyWorkView.java, octane-eclipse-plugin/src/com/hpe/octane/ideplugins/eclipse/ui/util/error/ErrorComposite.java
Apart from:
- get phase
- get&post comment
- my work 
- save button,
are there any other places where this error dialog / error composite should appear?
=> Custom roles error handling

octane-eclipse-plugin/src/com/hpe/octane/ideplugins/eclipse/ui/entitydetail/field/FieldEditorFactory.java, octane-eclipse-plugin/src/com/hpe/octane/ideplugins/eclipse/ui/entitydetail/field/ReferenceFieldEditor.java, octane-eclipse-plugin/src/com/hpe/octane/ideplugins/eclipse/ui/util/EntityComboBox.java
Had to add Entity.LIST_NODE, see [Common PR](https://github.com/MicroFocus/octane-plugin-common/pull/24)
Added proper support for selection handlers on EntityComboBox
Added Reference field editor, atm just contains an EntityComboBox
Created entity loader for list nodes based on metadata
=> Update reference list nodes

octane-eclipse-plugin/src/com/hpe/octane/ideplugins/eclipse/ui/util/icon/EntityIconFactory.java
Color correction for automated tests
=> Automated test color correction

octane-eclipse-plugin/src/com/hpe/octane/ideplugins/eclipse/ui/util/icon/EntityIconFactory.java
=> corrected test suite color

octane-eclipse-plugin/src/com/hpe/octane/ideplugins/eclipse/ui/util/icon/EntityIconFactory.java
conventions conventions conventions..
=> defect #637032: colors

octane-eclipse-plugin/src/com/hpe/octane/ideplugins/eclipse/ui/entitydetail/EntityFieldsComposite.java
=> Fixed big empty white space between label and editor if odd number of

octane-eclipse-plugin/src/com/hpe/octane/ideplugins/eclipse/ui/activeitem/ActiveEntityContributionItem.java, octane-eclipse-plugin/src/com/hpe/octane/ideplugins/eclipse/util/CommitMessageUtil.java
=> Added a sexy button, to generate and copy commit message easier

octane-eclipse-plugin/src/com/hpe/octane/ideplugins/eclipse/ui/util/error/ErrorComposite.java, octane-eclipse-plugin/src/com/hpe/octane/ideplugins/eclipse/ui/util/error/ErrorDialog.java
Defect 628050: now it is a scrollable text. Also increased default max size of dialog in order for the stack trace to look better.
=> Error dialog now wraps 

octane-eclipse-plugin/src/com/hpe/octane/ideplugins/eclipse/ui/mywork/MyWorkView.java, octane-eclipse-plugin/src/com/hpe/octane/ideplugins/eclipse/ui/util/error/ErrorComposite.java
Link to connection settings now appears when workspace breaks. 
Fast reproduction: 
- Login on eclipse plugin
- Go to spaces, change password for the current user
- Wait ~1min for sync 
- Refresh My work
=> Connection settings

octane-eclipse-plugin/src/com/hpe/octane/ideplugins/eclipse/ui/activeitem/ActiveEntityContributionItem.java
took me less then 20 minutes Andras!
=> Toolbar stop work

octane-eclipse-plugin/src/com/hpe/octane/ideplugins/eclipse/ui/entitydetail/EntityFieldsComposite.java
- make only one call to get the labels of each field
=> improves performance on entity fields rendering

octane-eclipse-plugin/src/com/hpe/octane/ideplugins/eclipse/preferences/PluginPreferencePage.java
=> defect #791034

octane-eclipse-plugin/src/com/hpe/octane/ideplugins/eclipse/Activator.java, octane-eclipse-plugin/src/com/hpe/octane/ideplugins/eclipse/util/EncodedAuthentication.java
: retrieves password from secure storage in ecliplse
=> user story #624043

octane-eclipse-plugin/src/com/hpe/octane/ideplugins/eclipse/ui/mywork/MyWorkEntityModelMenuFactory.java
[View in browser (System), View details, View parent details] **--->** [View details, View parent details, View in browser (System)] 
(to be like in intellij)
=> tech: change order of items in context menu in my work

octane-eclipse-plugin/src/com/hpe/octane/ideplugins/eclipse/ui/search/SearchEntityModelMenuFactory.java
View details <-> Open on browser (System) 
-> context menu from search tab
=> tech: change order of items from context menu in search tab

octane-eclipse-plugin/src/com/hpe/octane/ideplugins/eclipse/filter/UserItemArrayEntityListData.java, octane-eclipse-plugin/src/com/hpe/octane/ideplugins/eclipse/ui/entitydetail/field/FieldEditorFactory.java, octane-eclipse-plugin/src/com/hpe/octane/ideplugins/eclipse/ui/mywork/MyWorkEntityModelMenuFactory.java, octane-eclipse-plugin/src/com/hpe/octane/ideplugins/eclipse/ui/mywork/rowrenderer/MyWorkEntityModelRowRenderer.java, octane-eclipse-plugin/src/com/hpe/octane/ideplugins/eclipse/ui/util/OpenDetailTabEntityMouseListener.java
https://center.almoctane.com/ui/entity-navigation?p=1001/1002&entityType=work_item&id=1493041
This changes are made in order to adapt the code to the changes made in common module
=> defect #1493041: adapt code based on common changes

octane-eclipse-plugin/src/com/hpe/octane/ideplugins/eclipse/Activator.java
https://center.almoctane.com/ui/entity-navigation?p=1001/1002&entityType=work_item&id=1515104
**Problem:** After restart, the active editor in eclipse is empty
**Solution:** Refix the silly fix made for an older defect (all the editors icons that were not selected were not loaded) and use the restoreEditor(true) on all the editors that were not selected
=> defect #1515104: fix last opened tab after restart

octane-eclipse-plugin/src/com/hpe/octane/ideplugins/eclipse/ui/util/OpenDetailTabEntityMouseListener.java
https://center.almoctane.com/ui/entity-navigation?p=1001/1002&entityType=work_item&id=1525026
- add gherkin automated run comment to be able to open it on browser
=> defect #1525026: add gherkin automated run comment to be able to open it on browser

octane-eclipse-plugin/src/com/hpe/octane/ideplugins/eclipse/util/PredefinedEntityComparator.java
https://center.almoctane.com/ui/entity-navigation?p=1001/1002&entityType=work_item&id=1648045
added BDD to the entity comparator that is used when sorting the entities found in the filter list
=> defect #1648045: change order of entity list filter

octane-eclipse-plugin/src/com/hpe/octane/ideplugins/eclipse/Activator.java, octane-eclipse-plugin/src/com/hpe/octane/ideplugins/eclipse/util/EncodedAuthentication.java
- fix the name of the method which is used to get the password for the auth class 
(see also UserAuthentication)
=> defect #2261019: fix password getter from the store after IDE restarts
